version: '3.3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'rufobase'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '1919:3306'
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: dockette/adminer:full-php5
    ports:
      - '2020:8080'
volumes:
  my-db: