server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:1919/mysql?createDatabaseIfNotExist=true
    username: justRufet
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false